CONLESS_PACKETS_LIST_ENTRY(CLS_GETINFO, Getinfo, "getinfo", " ")
CONLESS_PACKETS_LIST_ENTRY(CLS_GETSTATUS, Getstatus, "getstatus", " ")
CONLESS_PACKETS_LIST_ENTRY(CLS_GETCHALLENGE, Getchallenge, "getchallenge", "")
CONLESS_PACKETS_LIST_ENTRY(CLS_CONNECT, Connect, "connect", " ")

CONLESS_PACKETS_LIST_ENTRY(CLS_GETSERVERS, Getservers, "getservers", " ")

CONLESS_PACKETS_LIST_ENTRY(CLS_GETINFO_RESPONSE, GetinfoResponse, "infoResponse", "\n")
CONLESS_PACKETS_LIST_ENTRY(CLS_GETSTATUS_RESPONSE, GetstatusResponse, "statusResponse", "\n")
CONLESS_PACKETS_LIST_ENTRY(CLS_GETCHALLENGE_RESPONSE, GetchallengeResponse, "challengeResponse", " ")
CONLESS_PACKETS_LIST_ENTRY(CLS_CONNECT_RESPONSE, ConnectResponse, "connectResponse", "")

CONLESS_PACKETS_LIST_ENTRY(CLS_GETSERVERS_RESPONSE, GetserversResponse, "getserversResponse", "\\")

CONLESS_PACKETS_LIST_ENTRY(CLS_RCON, Rcon, "rcon", " ")
CONLESS_PACKETS_LIST_ENTRY(CLS_PRINT, Print, "print", "\n")

CONLESS_PACKETS_LIST_ENTRY(CLS_DISCONNECT, Disconnect, "disconnect", "")